export { GameBase, type GameState, type GameActions } from './game-base'
export { DebugChallenge } from './debug-challenge'
export { OutputPredictionQuiz } from './output-prediction-quiz'
export { CodeOrderingPuzzle } from './code-ordering-puzzle'
export { MinigameModule, type MinigameType } from './minigame-module'
