apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-client
  labels:
    app: blazor-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor-client
  template:
    metadata:
      labels:
        app: blazor-client
    spec:
      containers:
        - name: blazor-client
          image: luxdecor/blazor-client:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blazor-client
spec:
  selector:
    app: blazor-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
