FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY src/ ./src/

RUN npm ci && npm run build

EXPOSE 3004

CMD ["node", "dist/main.calendar.js"]
